
# Environment
- name: Install NTP
  yum: name=chrony
- name: Copy chrony.conf
  template: src=../templates/chrony.conf dest=/etc/chrony.conf
- name: Start and Enable chrony
  systemd: name=chronyd.service enabled=True state=started
- name: Base pakgs
  yum: name={{ item }} state=present
  with_items:
    - libselinux-python
    - mysql-devel
    - gcc
    - python-devel
    - wget
    - vim
- name: download pip
  get_url: url=http://bootstrap.pypa.io/get-pip.py dest=/root/
- name: Installing pip
  command: python /root/get-pip.py 
- name: python for mysql
  pip: name=MySQL-python
- name: Disbling NetworkManager
  systemd: name=NetworkManager.service enabled=no state=stopped
- name: Configuring sysctl
  blockinfile:
    path: /etc/sysctl.conf
    block: |
      net.ipv4.ip_forward=1
      net.ipv4.ip_nonlocal_bind=1
- name: Reload sysctl
  command: sysctl -p
- name: Writing to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ controller }} controller
      {{ compute }} compute
      {{ cinder }} cinder
- name: Enable the OpenStack repository
  yum: name=centos-release-openstack-newton
#- name: Upgrade the packages on your host
#  yum: name="*" state=latest
- name: Install the OpenStack client
  yum: name={{ item }}
  with_items:
    - python-openstackclient
    - openstack-selinux
- name: Install and configure components
  yum: name={{ item }}
  with_items:
    - mariadb
    - mariadb-server
    - python2-PyMySQL
- name: Copy openstack.cnf
  template: src=../templates/openstack.cnf dest=/etc/my.cnf.d/openstack.cnf
- name: Start and Enable database service
  systemd: name=mariadb.service enabled=yes state=started
#- name: Mysql secure installation
#  shell: mysql_secure_installation
- name: Install Rabbitmq
  yum: name=rabbitmq-server
- name: Start and Enable Rabbitmq
  systemd: name=rabbitmq-server enabled=yes state=started

- name: Check Rabbit user for openstack
  shell: '[[ -z $(rabbitmqctl list_users|grep openstack) ]] && echo "not present" || echo "present"'
  register: rabbit_user_presence
  ignore_errors: True

- name: Add the openstack user and permissions
  shell: rabbitmqctl {{ item }}
  with_items:
    - add_user openstack {{ rabbit_pass }}
    - set_permissions openstack ".*" ".*" ".*"
  when: rabbit_user_presence.stdout == "not present"
  ignore_errors: True

- name: Install Memcached
  yum: name={{ item }}
  with_items:
    - memcached
    - python-memcached
- name: Copy /etc/sysconfig/memcached
  template: src=../templates/memcached dest=/etc/sysconfig/memcached
- name: Start and Enable Memcached
  systemd: name=memcached.service enabled=yes state=started
