- name: Create glance DB
  mysql_db: name=glance state=present
- name: Grant permissions to glance DB
  mysql_user: name=glance host={{ item }} password={{ glance_db_pass }} priv="glance.*:ALL,GRANT" state=present
  with_items:
    - controller
    - localhost

- name: Check if glance service entity exists
  shell: '[[ -z $(openstack service list|grep glance) ]] && echo "not present" || echo "present"'
  register: glance_service_presence
  environment: "{{ adminrc }}"

- name: Create the glance user
  command: openstack user create --domain default --password {{ glance_user_pass }} glance
  environment: "{{ adminrc }}"
  when: glance_service_presence.stdout == "not present"
  ignore_errors: True

- name: Add the admin role to the glance user and service project
  command: openstack role add --project service --user glance admin
  when: glance_service_presence.stdout == "not present"
  environment: "{{ adminrc }}"

- name: Create the glance service entity
  command: openstack service create --name glance --description "OpenStack Image" image
  environment: "{{ adminrc }}"
  when: glance_service_presence.stdout == "not present"

- name: Create the Image service API endpoints
  command: openstack endpoint create --region {{ region_one }} image {{ item }} http://controller:9292
  with_items:
    - public
    - internal
    - admin
  when: glance_service_presence.stdout == "not present"
  environment: "{{ adminrc }}"
  ignore_errors: True

- name: Install glance packages
  yum: name=openstack-glance

- name: Copy glance-api.conf
  template: src=../templates/glance-api.conf dest=/etc/glance/glance-api.conf
- name: Copy glance-registry.conf
  template: src=../templates/glance-registry.conf dest=/etc/glance/glance-registry.conf
- name: Populate the Image service database
  command: sh -c "glance-manage db_sync" glance

#- name: Setting directory permissions for /var/log/glance
#  file: path=/var/log/glance mode=0777 recurse=yes owner=glance group=glance
#  ignore_errors: True


- name: Enable and Start services
  systemd: name={{ item }} enabled=yes state=started
  with_items:
    - openstack-glance-api.service
    - openstack-glance-registry.service
